#!/usr/bin/env bash
#
# Configure tree-sitter paths for the osemgrep build.
#
# Generates tree-sitter-config.mk and tree-sitter-config.sh in the project
# root, pointing to either:
#   - a system-installed tree-sitter library (detected via pkg-config), or
#   - a locally built tree-sitter library (downloaded and built from source).
#
# This script is adapted from libs/ocaml-tree-sitter-core/configure but lives
# outside that submodule so it can add system tree-sitter auto-detection.
# The submodule's configure is not called; we replicate its output format here.
#
# Usage:
#   ./scripts/setup-tree-sitter.sh
#
# To force a local build even when system tree-sitter is present:
#   FORCE_LOCAL_TREE_SITTER=1 ./scripts/setup-tree-sitter.sh
#
set -eu

REQUIRED_VERSION="0.20"
OUTPUT_MK="tree-sitter-config.mk"
OUTPUT_SH="tree-sitter-config.sh"

write_config() {
  local incdir="$1" libdir="$2"

  cat > "$OUTPUT_MK" <<EOF
# Generated by scripts/setup-tree-sitter.sh
#
# Absolute paths to the tree-sitter installation folders.
# This file is meant to be included in makefiles.
#
TREESITTER_INCDIR := $incdir
TREESITTER_LIBDIR := $libdir
PKG_CONFIG_PATH := \$(TREESITTER_LIBDIR)/pkgconfig:\$(PKG_CONFIG_PATH)
export TREESITTER_INCDIR
export TREESITTER_LIBDIR
export PKG_CONFIG_PATH
EOF

  cat > "$OUTPUT_SH" <<EOF
# Generated by scripts/setup-tree-sitter.sh
#
# Absolute paths to the tree-sitter installation folders.
# Source this file before calling dune directly:
#
#   source ./tree-sitter-config.sh
#
TREESITTER_INCDIR="$incdir"
TREESITTER_LIBDIR="$libdir"
PKG_CONFIG_PATH=\$TREESITTER_LIBDIR/pkgconfig:\$PKG_CONFIG_PATH
export TREESITTER_INCDIR
export TREESITTER_LIBDIR
export PKG_CONFIG_PATH
EOF
}

use_system=false
if [ "${FORCE_LOCAL_TREE_SITTER:-}" != "1" ] \
   && command -v pkg-config >/dev/null 2>&1 \
   && pkg-config --exists tree-sitter \
   && pkg-config --atleast-version="$REQUIRED_VERSION" tree-sitter; then
  use_system=true
fi

if $use_system; then
  version=$(pkg-config --modversion tree-sitter)
  echo "Found system tree-sitter $version (>= $REQUIRED_VERSION), using it."
  incdir=$(pkg-config --variable=includedir tree-sitter)
  libdir=$(pkg-config --variable=libdir tree-sitter)
  write_config "$incdir" "$libdir"
else
  if [ "${FORCE_LOCAL_TREE_SITTER:-}" = "1" ]; then
    echo "FORCE_LOCAL_TREE_SITTER=1: skipping system tree-sitter check."
  else
    echo "System tree-sitter >= $REQUIRED_VERSION not found; building locally..."
  fi
  (cd libs/ocaml-tree-sitter-core \
     && ./scripts/install-tree-sitter-lib)
  local_prefix="$(pwd)/libs/ocaml-tree-sitter-core/tree-sitter"
  write_config "$local_prefix/include" "$local_prefix/lib"
fi
